export default {
    BUSINESSKPI: "Business KPI",
    ROLE_SALE_PERSON: 1,
    ROLE_MANAGER: 2,
    ROLE_REGIONAL_MANAGER: 3,
    ROLE_HEAD_MANAGER: 4,
    ROLE_HQ_USER: 5,
    ROLE_ADMINISTRATOR: 6,
    ROLE_HQSALES_MANAGER: 8,
    TAB_INDIVIDUAL: "Individual",
    UPDATED_DATE: "- Updated as of",
    TAB_TEAM: "Team",
    BANK_RATES: "Bank Rates",
    MALAYSIA: "Malaysia",
    UPLOAD_LEAD_INFORMATION: "Lead File Upload",
    PRODUCT_INFORMATION_PAGE: "Product Information Page",
    UPLOAD_CUSTOMER_MASTER_INFORMATION: "Customer File Upload",
    UPLOAD_PERFORMANCE_INFORMATION: "Performance File Upload",
    ERROR_ASSIGN_USER: "Sales Person is mandatory",
    ERROR_NO_INTERNET: "No Internet, please check connection",
    ERROR_SEARCH_CUSTOMER: "Company not recognised, please create new customer record",
    ERROR_PRODUCT_TYPE: "Please select product type",
    ERROR_QUESTION_LOAN: "Please select answer",
    ERROR_QUESTION_TURN_OVER: "Please select answer",
    ERROR_SME_PRODUCTS: "SME products or Cross-selling is mandatory",
    ERROR_CROSS_SELLING_PRODUCTS: "Cross-selling products is mandatory",
    ERROR_CATEGORY: "Category is mandatory",
    ERROR_DIVISION_CODE: "Division Code is mandatory",
    ERROR_ACCOUNT_TYPE: "Account type is mandatory",
    ERROR_STATUS: "Status is mandatory",
    ERROR_COMPANY_NAME: "Company Name is mandatory and alpha numeric",
    ERROR_COMPANY_REG_NO: "Company Reg. No is mandatory and alpha numeric",
    ERROR_CONTACT_NUMBER: "Contact Number is mandatory and numeric",
    ERROR_FIRST_LINE_ADDRESS: "Address line 1 is mandatory",
    ERROR_SECOND_LINE_ADDRESS: "Address line 2 is mandatory",
    ERROR_THIRD_LINE_ADDRESS: "Address line 3 is mandatory",
    ERROR_CIF: "CIF is mandatory",
    ERROR_POSTAL_CODE: "Postal Code is mandatory and numeric",
    ERROR_INDUSTRY: "Industry is mandatory",
    ERROR_CONTACT_NAME: "Contact Name is mandatory and alpha numeric",
    ERROR_CONTACT_EMAIL: "Contact Email is mandatory and email",
    ERROR_CONTACT_BUSINESS: "Contact Business is mandatory and numeric",
    ERROR_DIRECTOR_NAME: "Director Name is mandatory and alpha numeric",
    ERROR_DIRECTOR_EMAIL: "Director Email is mandatory and email",
    ERROR_DIRECTOR_NUMBER: "Director Number is mandatory and numeric",
    ERROR_DIRECTOR_BUSINESS: "Director Business is mandatory and numeric",
    ERROR_DIRECTOR_DUPLICATE: "Oops. Customer has already active lead being pursued by another user",
    ERROR_CONTACT_DUPLICATE: "Oops. Customer director already exists with given details",
    ERROR_POTENTIAL_VALUE: "Potential value is mandatory and numeric",
    ERROR_EMPTY_POCS: "Please add at least one Point of Contact",
    ERROR_EMPTY_DIRECTORS: "Please add at least one Director",
    ERROR_COMPANY_TYPE: "Company Type is mandatory",
    ERROR_CITY: "City is mandatory and alpha numeric",
    ERROR_STATE: "State is mandatory",
    ERROR_NOTE_DESCRIPTION: "Notes is mandatory",
    ERROR_PURPOSE_MEETING: "Purpose is mandatory",
    ERROR_STATUS_MEETING: "Status is mandatory",
    ERROR_STREET_MEETING: "Street is mandatory",
    ERROR_POSTAL_CODE_MEETING: "Postal Code is mandatory and numeric",
    ERROR_CITY_MEETING: "City is mandatory",
    ERROR_CONTACT_TYPE: "Point of Contact Type is mandatory",
    ERROR_REMOVE_DIRECTOR: "Director can not empty",
    ERROR_REMOVE_POC: "Point of contact can not empty",
    EMPTY_INPUT_FIELD: "This field is required",
    ERROR_SUPPLIER_DAYS: "Supplier Days must be numeric",
    ERROR_RECEIVABLE_DAYS: "Receivable Days must be numeric",
    ERROR_INVENTORY_DAYS: "Inventory Days must be numeric",
    ERROR_MONTHLY_REVENUE: "Monthly Revenue must be numeric",
    ERROR_GROSS_PROFIT_MARGIN: "Gross Profit Margin must be decimal",
    ERROR_WORKING_CAPITAL_EXISTING: "Existing Working Capital must be numeric",
    ERROR_ACCOUNTS_PAYABLE: "Account Payables must be numeric",
    ERROR_PAYABLE_COST: "Cost of Goods Sold must be numeric",
    ERROR_INVENTORY: "Inventory must be numeric",
    ERROR_INVENTORY_COST: "Cost of Goods Sold must be numeric",
    ERROR_ACCOUNTS_RECEIVABLE: "Accounts Receivable must be numeric",
    ERROR_RECEIVABLE_REVENUE: "Annual Revenue must be numeric",
    ERROR_TOTAL_LIMIT: "Trade Limit must be numeric",
    ERROR_INTEREST_RATE: "Interest Rate must be decimal",
    ERROR_COMMITMENT_FEE: "Commitment Fee must be decimal",
    ERROR_LIMIT: "Limit must be numeric",
    ERROR_TRANSACTION_AMOUNT: "Transaction Amount must be numeric",
    ERROR_DAY_IN_MONTH: "Day in Month must be numeric",
    ERROR_MONTH_MAX_DAY: "Maximum of 31 days only",
    ERROR_NEW_WITHDRAWAL: "Numeric values",
    ERROR_SIMULATOR: "Please make sure all the fields are filled correctly.",
    ERROR_STAFF_ID: "Staff ID is mandatory. Should be 6 digit numeric code",
    ERROR_PHONE_NUMBER: "Phone number is numeric",
    ERROR_USER_ROLE: "Choose User Role is mandatory",
    ERROR_STATUS_REASON: "Reason is mandatory",
    ERROR_PARTIALLY_SUBMITTED_PRODUCT: "Please select at lease one product",
    ERROR_MANAGER: "Choose Reporting manager is mandatory",
    ERROR_REPLACEMENT_MANAGER: "Choose Replacement manager is mandatory",
    ERROR_REGION: "Choose Region is mandatory",
    ERROR_TEAM: "Choose Team is mandatory",
    ERROR_USER_NAME: "Full name is mandatory",
    ERROR_USER_EMAIL: "Email address is mandatory",
    ERROR_FILTER_USERS: "Please select a user role",
    ERROR_FORMAT_FILE: "File upload only support file format .xlsx",
    ERROR_FORMAT_SUPPORT_DOC: "Allowable file formats are PDF, DOC, DOCX, JPG, JPEG",
    ERROR_FORMAT_DOC_REPO: "Uploaded file format needs to be in PDF",
    ERROR_SIZE_DOCUMENT: "Maximum File size is 2.5 MB per file",
    ERROR_NAME_DOC_EXIST: "This file name is already exists in system, please use another file name.",
    ERROR_PRODUCT_ID_EXIST: "This Product Identifier is already exists in system, please use an unique value for Product Identifier.",
    ERROR_PRODUCT_ID: "Please enter product identifier",
    ERROR_PRODUCT_NAME: "Please enter product name",
    ERROR_PRODUCT_CATEGORY: "Please select from dropdown menu",
    ERROR_PRODUCT_DESCRIPTION_TITLE: "Please enter section title ",
    ERROR_PRODUCT_DESCRIPTION_CONTENT: "Please enter section content ",
    ERROR_PRODUCT_SPECIALIST_NAME: "Please enter agent name",
    ERROR_PRODUCT_SPECIALIST_JOB_TITLE: "Please enter primary job title",
    ERROR_PRODUCT_SPECIALIST_PHONE: "Please enter contact number",
    ERROR_PRODUCT_SPECIALIST_EMAIL: "Please enter email address",
    ERROR_NO_SEARCH_CUSTOMER: "Oops! Your searched customer not found",
    ERROR_CUSTOMER_ADD_POINT_OF_CONTRACT:
        'Please fill in all mandatory fields(*) and click on "Add point of contact" button before saving the customer',
    ERROR_NOTIFICATION_CONTENT: "Notification content is mandatory",
    ERROR_NOTIFICATION_USER: "Please select user",
    SUCCESS_ASSIGN_LEADS: "Assign leads are successfully",
    SUCCESS_REASSIGN_LEADS: "Reassign leads are successfully",
    SUCCESS_UPDATE_LEAD: "You have successfully updated a lead",
    SUCCESS_LEAD: "You have successfully created a lead for ",
    SUCCESS_USER: "You have successfully created a User ",
    SUCCESS_SAVE_PERMISSIONS: "You have successfully updated permissions ",
    SUCCESS_EDIT_USER: "Changes Saved ",
    SUCCESS_UPDATED_DOCUMENT: "You have successfully updated document",
    SUCCESS_DELETE_DOCUMENT: "You have successfully deleted document",
    SUCCESS_UPLOAD_DOCUMENT: "You have successfully uploaded document",
    SUCCESS_ADDED_DOCUMENT: "You have successfully added document",
    SUCCESS_SENDED_NOTIFICATION: "You have successfully sent notification",
    SUCCESS_RESENDED_NOTIFICATION: "You have successfully resent notification",
    SUCCESS_CREATE_NEWS: "You have successfully create news",
    FAILURE_CREATE_NEWS: "You unable to create news",
    SUCCESS_PUBLISH_NEWS: "You have successfully published news",
    SUCCESS_UNPUBLISH_NEWS: "You have successfully unpublished news",
    FAILURE_PUBLISH_NEWS: "You unable to publish news",
    SUCCESS_DELETE_NEWS: "You have successfully deleted news",
    FAILURE_DELETE_NEWS: "Delete news error",
    SUCCESS_SHOWCASE_NEWS: "You have successfully enabled showcase news",
    SUCCESS_DIS_SHOWCASE_NEWS: "You have successfully disabled showcase news",
    FAILURE_SHOWCASE_NEWS: "Enable showcase error",
    FAILURE_USER: "You are unable to create a User",
    SUCCESS_HQ_USER: "You have successfully created a HQ User ",
    FAILURE_HQ_USER: "You are unable to create a HQ User",
    SUCCESS_MEETING_NOTES: "You have successfully create a meeting notes with purpose ",
    FAILURE_LEAD: "You are unable to create a lead for ",
    FAILURE_LEAD_EDIT: "You are unable to edit lead",
    TRY_AGAIN: "Please try again",
    FAILURE_CUSTOMER_01: "You are unable to create a customer profile for ",
    FAILURE_CUSTOMER_02: " as customer already exist in database",
    SUCCESS_EDIT_PRODUCT: "You have successfully updated a product",
    SUCCESS_PRODUCT: "You have successfully created a product ",
    SUCCESS_CUSTOMER: "You have successfully created a customer ",
    SUCCESS_UPDATE_CUSTOMER: "You have successfully updated a customer ",
    SUCCESS_UPDATE_MEETING_NOTE: "You have successfully updated a meeting notes",
    SUCCESS_SHARE_MEETING_NOTE: "You have successfully shared a news article",
    SUCCESS_SHARE_MEETING_NOTE_DETAIL: "You have successfully shared a meeting note",
    SUCCESS_SHARE_PRODUCT: "You have successfully shared product",
    SUCCESS_CONTACT_SPECIALIST_PRODUCT: "You have successfully contact the specialist product",
    SUCCESS_FILE_UPLOAD: "You have successfully uploaded file",
    SUCCESS_DEACTIVE_TEMP_USER: "You have successfully de-active temporary user",
    SUCCESS_REACTIVE_TEMP_USER: "You have successfully re-active temporary user",
    SUCCESS_DEACTIVE_PERMANENT_USER: "You have successfully deactived user permanently",
    SUCCESS_SEND_EMAIL: "Email has been successfully sent to ",
    SUCCESS_SAVE_CONFIG: "You have successfully save configuration",
    FAILTURE_SEND_EMAIL: "Send email error",
    CUSTOMER_NOT_INTERESTED: "Customer Not Interested",
    CUSTOMER_UNSUITABLE: "Customer Unsuitable",
    CUSTOMER_DECLINED_OFFER: "Customer Declined Offer",
    PENDING_INITIAL_CONTACT: "Pending Initial Contact",
    FIRST_MEETING_SCHEDULED: "First Meeting Scheduled",
    ONE_MEETING_SCHEDULED: "1st Meeting Scheduled",
    FOLLOW_UP_MEETING_SCHEDULED: "Follow Up Meeting Scheduled",
    FOLLOW_UP_MEETING_SCHEDULED_1: "Follow-up Meeting Scheduled",
    APPLICATION_INITIATED: "Application Initiated",
    APPLICATION_SUBMITTED: "Application Submitted",
    PARTIALLY_SUBMITTED: "Partially Submitted",
    CLOSED_BY_SYSTEM: "Closed By System",
    KEEP_IN_VIEW: "Keep In View",
    CONVERTED: "Converted",
    CUSTOMER_UNREACHABLE: "Customer Unreachable",
    APPLICATION_REJECTED: "Application Rejected",
    EXISTS_NAME_DOCUMENT: "Name already exist. Please try another name",
    PAGE_SIZE: 10,
    THIS_WEEK: "This Week",
    LAST_WEEK: "Last Week",
    THIS_MONTH: "This Month",
    THIS_QUARTER: "This Quarter",
    LAST_QUARTER: "Last Quarter",
    LAST_12_MONTHS: "Last 12 Months",
    PRIORITY: "Priority",
    STATUS_ALL: "All",
    ASSIGNED: "Assigned",
    DUE_SOON: "Due soon",
    OVERDUE: "Overdue",
    STATUS_GENERATED: "Generated",
    STATUS_CONTACTED: "Contacted",
    STATUS_SUBMITTED: "Submitted",
    STATUS_CONVERTED: "Converted",
    STATUS_CLOSED: "Closed",
    PRIORITY_ALL: "All",
    PRIORITY_LIGHTNING_BOTH: "Lightning bolt",
    PRIORITY_STARRED: "Starred",
    PRIORITY_UNSTARRED: "Unstarred",
    READ: "Read",
    UN_READ: "Unread",
    READ_UN_READ_ALL: "All",
    ACTION_ACTIVE: "Active",
    ACTION_INACTIVE: "Inactive",
    ACTION_ALL: "All",
    SOURCE_ALL: "All",
    MANUAL: "Manual",
    WEEK: "Week",
    MONTH: "Month",
    YEAR: "Year",
    ROLE: "Role",
    MTD: "MTD",
    YTD: "YTD",
    FILETYPE: "Actual",
    COMMISSION: "Commission",
    CROSS_SELL: "Cross sell",
    PRODUCTIVITY: "Productivity",
    FINANCIALKPI: "Financial KPI",
    ASSETQUALITY: "Asset Quality",
    UNASSIGNED: "Unassigned",
    REASSIGNED: "Reassigned",
    LEAD_TYPE_ALL: "All",
    MSG_NOTIFICATION_ASSIGN: "Please Unassign the lead first before Reassigning to another user",
    MSG_CONFIGURATION_UPDATE:
        "You are about to apply changes on configurations. Are you sure that you want to continue and apply the changes?",
    MSG_CONFIRM: "Are you confirm that you want to upload this file ?",
    MSG_OVERRIDE: "The file you are intending to upload already exist in the system. Are sure you want to overwrite this file ?",
    MSG_DELETE_SUPPORT_DOC: "Are you sure you would like to delete this Supporting Document?",
    LEAD_TYPE_SALE_TEAM: "Sales Team",
    NO_USERS_FOUND: "No search results found.",
    FETCHING_USERS: "Fetching users",
    ERROR_FILE_UPLOAD: "Please select file to upload",
    ERROR_FILE_UPLOAD_DROPDOWN: "Please select the dropdown values",
    SOURCE_MANUAL_CREATION: "Manual Creation",
    SOURCE_ANALYTICS: "Analytics",
    LOGIN_USER_ID: "cf1af86KL17907ba6006skkl531",
    STAFF_ID: "198350",
    USER_ID: "cf1af86KL17907ba6006skkl531",
    INIT_LEAD_USER_ID: "443reetrrr334423rtssafdsaewef",
    SME: "SME",
    NON_SME: "NON SME",
    LEAD_CONFIRM_PARTIAL_SUBMIITED: "Please create a new lead for the unsubmitted products",
    LEAD_CONFIRM_EXIT: "You have not created a new lead for the unsubmitted products yet. Are you sure you want to exit?",
    CUS_CONFIRM_EXIT: "You have not created a new customer. Are you sure you want to exit?",
    PROD_CONFIRM_EXIT:
        'Your changes have not been saved. Are you sure you want to exit? Please click the "Save Product" button before exiting to save your changes.',
    MSG_CONFIRM_FILE_UPLOAD: "You are about to upload {1} as {2}. Would you like to continue?",
    MSG_CONFIRM_FILE_DOWNLOAD_DATE: "Please select from date and to date",
    MSG_CONFIRM_EXIT_USER_PAGE: "Your changes have not been saved yet, are you sure you want to leave this page?",
    MSG_CONFIRM_CANCEL_CHANGES: "Are you sure you want to cancel the changes?",
    MSG_CONFIRM_DEACTIVE_PERMANENT:
        "Warning. You are about to de-activate {1} permanently. User will not be able to log in and all active leads tagged to user will be closed or unassigned. Are you sure that you would like to de-activate {2} permanently ?",
    MSG_CONFIRM_NOTIFICATION: "Are you sure you want to notify message to users?",
    HEALTHCHECK_DISCLAIMER:
        "RHB Bank accepts no liability for any inaccuracies and/or omissions on this Health Check function, and any decision made based on the information contained on Health check is the sole responsibility of the person concerned.",
    SENT_EMAIL_ACTIVE_LEAD: "Email sent successfully to current active lead",
    MSG_CONFIRM_DELETE_NEW: "Are you sure to delete news ?",
    ERROR_LEAD_REMARK_MAX_LENGTH: "Max limit 750 characters only",
    ERROR_MEETING_NOTE_MAX_LENGTH: "Max limit 1000 characters only",
    MSG_CONFIRM_DELETE_ITEM: "Are you sure to delete this item ?",
    MSG_DEL_LEAD_CATEGORY: "Are you sure you want to delete this lead category ?",
    MSG_DEL_MEETING_NOTES: "Are you sure you want to delete this meeting note purpose ?",
    MSG_DEL_LEAD_CLOSURE: "Are you sure you want to delete this lead closure reason?",
    DATA_NOT_FOUND: "Data not found",
    ERROR_EXCUTE_API: "Error",
    SALE_MANAGER_MARK_SIVIT_CONFIRM: "Do you want to mark on-site visit report ?",
    EMAIL_CONTENT: (docName) => `As requested, Please find the below ${docName} attachments.`,
    ERROR_CONTACT_NUMBER_WITH_STATE_CODE: 'Contact Number Should Have "+60" Prefix',
    // DESCRIPTION OF USER HQ TYPE
    ROLE_HQ_LEADS: "HQ Leads",
    ROLE_HQ_BENCHMARK: "HQ Benchmark",
    ROLE_HQ_NEWS: "HQ News And Comms",
    ROLE_HQ_PERFORMANCE: "HQ Performance",
    ROLE_HQ_PRODUCT: "HQ Products",
    ROLE_HQ_SALES_MANAGER: "HQ Sales / L2+ / Sales Manager",
    ROLE_HQ_SYS_OPS: "HQ Sys Ops",
    ERROR_PRODUCT_AVAILABILITY: "You have to choose availability",
    ERROR_PRODUCT_EXIST: "The Product is already exist",
    ERROR_SPECIALIST_NAME: "Specialist Name cannot be empty",
    ERROR_SPECIALIST_JOB: "Specialist Job cannot be empty",
    ERROR_SPECIALIST_CONTACT: "Specialist Contact cannot be empty",
    ERROR_SPECIALIST_EMAIL: "Specialist Email cannot be empty",
    ERROR_SPECIALIST_CCEMAIL: "Specialist CCEmail cannot be empty",
    ERROR_PRODUCT_DISCLAIMER: "Product Disclaimer cannot be empty",
};
